language: go
go:
  - tip
addons:
  apt:
    packages:
      - strace
      - graphviz
before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get github.com/bradfitz/goimports
  - go get github.com/golang/lint/golint
  - go get golang.org/x/tools/cmd/vet
  - if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
  - git clone https://gist.github.com/0f22736320abe6be71ce.git $HOME/goclean
script:
  - ./goclean.sh
  - $HOME/gopath/bin/goveralls -coverprofile=profile.cov -service=travis-ci
