sudo: required # required by tup, as he uses /dev/fuse
language: go
go:
  - tip
addons:
  apt:
    packages:
      - strace
      - graphviz
      - libfuse-dev
before_install:
  - git clone git://github.com/gittup/tup.git $HOME/tup
  - (cd $HOME/tup; ./bootstrap.sh)
script:
  - mkdir ~/vim-test
  - cd ~/vim-test
  - PATH=$PATH:$HOME/tup $TRAVIS_BUILD_DIR/scripts/vim-test
